### ISSUE TITLE
C3D has worked for the first time

### ISSUE THREAD

**Issue by carsonDB** [carsonDB/video_tempo#1]
### I ran the network with:
- 4 conv layers (each following RELU and Max Pooling)
- 2 fully connected layers
### dataset: UCF-11

Here is the training result after running for 18 hours.

[C3D_train.tar.gz](https://github.com/carsonDB/Tempo/files/436703/C3D_train.tar.gz)

**Comment by zbwglory** [comment]
It looks fine for me. For the arch, it should be conv->pool->ReLU. You can now try to run UCF-101 split1. You should follow the arch of the girl's paper.

**Comment by carsonDB** [comment]
@zbwglory 
Fine, I'll tune my parameters in correspondence with that paper's.

But as for the order of layers.
Here is a quote from that paper (at page 4).

> Each convolutional layer is followed by a
> rectified linear unit (ReLU) and a space-time max pooling layer
