### ISSUE TITLE
Some video is not long enough.

### ISSUE THREAD

**Issue by carsonDB** [carsonDB/video_tempo#2]
I train C3D network with 60f a clip.
But I found out that **/JumpingJack/v_JumpingJack_g14_c04**
has only 59 frames.

So what should I do next ?

**Comment by zbwglory** [comment]
You can overlap sample these videos

**Comment by carsonDB** [comment]
@zbwglory 
You mean after sampling the end frame of that video, I should sample
the first frame and second... of that video again ?
