### ISSUE TITLE
Different iterations

### ISSUE THREAD

**Issue by carsonDB** [carsonDB/video_tempo#7]
In LTC paper,

> For 16f networks, the first decrease is after 80K iterations and
> the second one after 45K additional iterations. The optimization is completed
> after 20K more iterations.

But in config of C3D (caffe):

> stepsize: 20000
> max_iter: 60000

**Comment by zbwglory** [comment]
the result should be similar.  You can follow either

**Comment by carsonDB** [comment]
Fine, I just follow C3D version.
