### ISSUE TITLE
I found a tensorflow model transfered from C3D (caffe)

### ISSUE THREAD

**Issue by carsonDB** [carsonDB/video_tempo#9]
Here is the same situation that I meet.
[https://github.com/facebook/C3D/issues/137](url)
And the transfered model is here:
[https://github.com/hx173149/C3D-tensorflow](url)

I just found there are a bunch of dirty works to transfer.
So, if this transfered model works out the same result as mine,
maybe I think my model is just fine.

**Comment by zbwglory** [comment]
okay so just try it and tell me the result

**Comment by carsonDB** [comment]
@zbwglory 
Although that transferred model is actually written by hand (not directly transferred from C3D caffe version) as I did and that codes are unly and bad-quality,
I tested my model with that one anyway.

The result losses of first iteration are pretty close (differ with 0.0X).
